### ISSUE TITLE
Missing prototypes of ONE Structure and SOME Functions.

### ISSUE THREAD

**Issue by dongfreelancer** [jthuraisamy/SysWhispers2#1]
_I found some new functions were added in the newest Windows 10 build. But I can't look for their document. Will write the undocumented functions and a structure._

**Functions:** 
`NtPssCaptureVaSpaceBulk, NtAllocateUserPhysicalPagesEx, NtAcquireCrossVmMutant, NtCreateCrossVmMutant, NtDirectGraphicsCall, NtWriteErrorLogEntry, NtCreateWinStation, NtOpenWinStation, NtSetWinStationInformation, NtQueryWinStationInformation`

**Type:** 
`CHANNEL_MESSAGE`

**Comment by odzhan** [comment]
Please make a pull request for any missing prototypes.
