### ISSUE TITLE
can't compile project - cannot convert argument 4 from "PULONG" to "PSIZE_T"

### ISSUE THREAD

**Issue by slavadba** [jthuraisamy/SysWhispers2#10]
Hi,

I take example code from your description (how inject DLL) but  get 2 errors during compilation-  both on line

NtAllocateVirtualMemory(hProcess, &lpAllocationStart, 0, (PULONG)&szAllocationSize, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);

Errors :
1 ) argument of type "PULONG" is incompatible with parameter of type "PSIZE_T"
2 ) cannot convert argument 4 from "PULONG" to "PSIZE_T"

All code and the errors can be seen on the link https://ibb.co/JzrBx4y

**Comment by physics-sec** [comment]
Try making allocationSize ULONG type

**Comment by odzhan** [comment]
The prototype for NtAllocateVirtualMemory is defined on MSDN.

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntallocatevirtualmemory

From the picture, it looks like you're casting from PSIZE_T to PULONG. Remove the cast and should compile fine.
