### ISSUE TITLE
Undo commit 2689d07c8dbe9ca50e76a10076a2c203d977bc0b

### ISSUE THREAD

**Issue by b0rnh4ck** [jthuraisamy/SysWhispers2#21]
Commit 2689d07c8dbe9ca50e76a10076a2c203d977bc0b should be reverted. "RtlCreateUserThread" is (obviously) not a syscall and, even if it was, the prototype is incorrect for x64 usage.

**Comment by odzhan** [comment]
Please make a pull request.
