### ISSUE TITLE
NtWriteVirtualMemory x86 - not working

### ISSUE THREAD

**Issue by geometry88** [jthuraisamy/SysWhispers2#26]
does not want to work in any NtWriteVirtualMemory x86

NtReadVirtualMemory works good

**Comment by odzhan** [comment]
If you're certain NtReadVirtualMemory works fine, why would you think something is wrong with NtWriteVirtualMemory? Did you check the NTSTATUS of each syscall? Seems like whatever you're trying to write to isn't writeable. So you might need to use NtProtectVirtualMemory before NtWriteVirtualMemory. You could also try using WriteProcessMemory which removes and restores the protection internally.

**Comment by geometry88** [comment]
> If you're certain NtReadVirtualMemory works fine, why would you think something is wrong with NtWriteVirtualMemory? Did you check the NTSTATUS of each syscall? Seems like whatever you're trying to write to isn't writeable. So you might need to use NtProtectVirtualMemory before NtWriteVirtualMemory. You could also try using WriteProcessMemory which removes and restores the protection internally.

You are right, write protection has been set, thank you for the prompt response!
