### ISSUE TITLE
NtCreateThreadEx crashes the process

### ISSUE THREAD

**Issue by philross88** [jthuraisamy/SysWhispers2#3]
I have spent quite a few hours in debugging and finally nailed down why process injection is failing. The call to NtCreateThreadEX using SysWhispers2 isn't really working for me. The process crashes as soon as the thread is injected.

My code is very simple that I open the process using Pid, create a virtual memory and then create RemoteThreadEX. I have ported all the calls to Syswhispers from High level APis but when I call NtCreateThreadEX, the process is crashing. When I just call CreateRemoteThread Directly, it works fine.

This is how I am calling the function 
NtCreateThreadEx(&hThread, GENERIC_EXECUTE, NULL, process_handle, pointer_after_allocated, pointer_after_allocated, FALSE, NULL, NULL, NULL, NULL);

I am trying to follow this tutorial but in my code, I take PID to inject.
https://sevrosecurity.com/2020/04/08/process-injection-part-1-createremotethread/

**Comment by odzhan** [comment]
replace [this](https://github.com/jthuraisamy/SysWhispers2/blob/22698f0bfa82e945304117a4ff33968ca59ef414/syswhispers.py#L136) with the following.

```
    def _get_function_asm_code(self, function_name: str) -> str:
        function_hash = self._get_function_hash(function_name)

        # Generate 64-bit ASM code.
        code = ''
        code += f'{function_name} PROC\n'
        code += '\tmov [rsp +8], rcx          ; Save registers.\n'
        code += '\tmov [rsp+16], rdx\n'
        code += '\tmov [rsp+24], r8\n'
        code += '\tmov [rsp+32], r9\n'
        code += '\tsub rsp, 28h\n'
        code += f'\tmov ecx, 0{function_hash:08X}h        ; Load function hash into ECX.\n'
        code += '\tcall SW2_GetSyscallNumber  ; Resolve function hash into syscall number.\n'
        code += '\tadd rsp, 28h\n'
        code += '\tmov rcx, [rsp +8]          ; Restore registers.\n'
        code += '\tmov rdx, [rsp+16]\n'
        code += '\tmov r8, [rsp+24]\n'
        code += '\tmov r9, [rsp+32]\n'
        code += '\tmov r10, rcx\n'
        code += '\tsyscall                    ; Invoke system call.\n'
        code += '\tret\n'
        code += f'{function_name} ENDP\n'

        return code

```

**Comment by odzhan** [comment]
Code has been updated.

**Comment by philross88** [comment]
NTCreateThreadEx is still crashing after the code update. I can call createRemoteThread successfully and it works however, when i use syscall as mentioned above, the process crashes.

**Comment by odzhan** [comment]
Can you upload some code for reviewing? It works for me. However, it may be a misligned data structure or stack.

**Comment by odzhan** [comment]
The following based on the example in the readme file worked.

```
void 
InjectDll(const HANDLE hProcess, const char* dllPath)
{
    HANDLE hThread = NULL;
    LPVOID lpAllocationStart = NULL;
    SIZE_T szAllocationSize = lstrlenA(dllPath);
    LPVOID lpStartAddress = GetProcAddress(GetModuleHandleA("kernel32.dll"), "LoadLibraryA");
    NTSTATUS Status;
    
    Status = NtAllocateVirtualMemory(
      hProcess, 
      &lpAllocationStart, 
      0, 
      &szAllocationSize, 
      MEM_COMMIT | MEM_RESERVE, 
      PAGE_EXECUTE_READWRITE
      );
      
    if(!NT_SUCCESS(Status)) {
      printf("NtAllocateVirtualMemory failed : %08lX\n", Status);
      goto Cleanup;
    }
    
    Status = NtWriteVirtualMemory(
      hProcess, 
      lpAllocationStart, 
      (PVOID)dllPath, 
      lstrlenA(dllPath), 
      NULL
      );
      
    if(!NT_SUCCESS(Status)) {
      printf("NtWriteVirtualMemory failed : %08lX\n", Status);
      goto Cleanup;
    }
    
    Status = NtCreateThreadEx(
      &hThread, 
      THREAD_ALL_ACCESS, 
      NULL, 
      hProcess, 
      lpStartAddress, 
      lpAllocationStart, 
      FALSE, 
      0, 
      0, 
      0, 
      NULL
      );
      
    if(!NT_SUCCESS(Status)) {
      printf("NtCreateThreadEx failed : %08lX\n", Status);
    }
Cleanup:
    if(lpAllocationStart) {
      NtFreeVirtualMemory(
        hProcess,
        &lpAllocationStart,
        0,
        MEM_RELEASE
        );
    }
    printf("Leaving. Status : %s\n", 
      NT_SUCCESS(Status) ? "OK" : "FAILED");
}
```

**Comment by philross88** [comment]
Thanks, I also found the issues. pointer_after_allocated has to be assigned to nullptr. I guess it became a dangling pointer during the testing and therefore was causing the issue.
