### ISSUE TITLE
Moving from SysWhispers1 to SysWhispers2

### ISSUE THREAD

**Issue by ghost** [jthuraisamy/SysWhispers2#4]
Correct me if im wrong but from what i understand to move from 1 -> 2 all i should have to do is replace .h file on the #include part of my code if the code using SysWhispers1 was working with that old .h syscalls file?
I ask because im getting a error when using x86_64-w64-mingw32. Error is "Undefined reference to '{INSERT syscall NAME}'

**Comment by ORCA666** [comment]
@ceramic-skate0 
Im having the same problem, when u figure it out please till me !!! 👀

**Comment by ghost** [comment]
nvm 3 is out now
